[workspace]
members = [ "common", "daemon", "overlay"]
resolver = "2"


[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.81"
async-watcher = "0.3.0"
axum-codec = { version = "0.0.12", default-features = false, features = ["cbor"] }
config = "0.14"
dirs = "5.0.1"
futures = "0.3"
http = "1.1.0"
native-windows-gui = "1.0.12"
reqwest = { version = "0.12", features = ["json"] }
reqwest-middleware = "0.3.3"
sea-query = {version = "0.31.0", features = ["derive"]}
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "migrate"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "fs"] }
windows = {version = "0.58.0", features = ["Win32_UI_WindowsAndMessaging", "Foundation", "Win32_Graphics_Gdi"]}
windows-strings = "0.1.0"
sysinfo = "0.31.3"
