[dist.dependencies.homebrew]
pango = "*"
gobject-introspection = "*"

[dist.dependencies.apt]
libgtk-4-dev = '*'
libglib2.0-dev = "*"

[dist.dependencies.chocolatey]
libgtk-4-dev = '*'
libglib2.0-dev = "*"
pkgconfiglite = "*"
