[package]
name = "cephalon_rust_overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.12.1", features =["tokio", "canvas","debug"]}
iced_layershell = "0.5.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "fs"] }
